batch-executer.title=Batch Executer
batch-executer.intro-text=Jobs currently executed by the batch executer.
batch-executer.none=There are no jobs running now.
batch-executer.column.name=Name
batch-executer.column.batchSize=Batch Size
batch-executer.column.threads=Threads
batch-executer.column.disabledRules=Disabled Rules
batch-executer.column.completed=Completed
batch-executer.column.total=Total
batch-executer.column.nodeFunction=Node Function
batch-executer.column.batchFunction=Batch Function
batch-executer.column.status=Status
batch-executer.column.action=Action
batch-executer.cancel=Cancel
batch-executer.canceled-prefix=Job
batch-executer.canceled=was canceled.
batch-executer.already-finished=has already finished or was canceled before.
